#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

read -p "Are you sure you want to upload (yes/no, default: yes): " answer

case $answer in
	*n*)
		echo "OK, exiting"
		;;
	*)
		echo "Uploading"
        git push origin "$(git symbolic-ref --short HEAD)"
		;;
esac

exit 0
